import type { NextPage } from "next";
import Head from "next/head";
import HomePage from "./home";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Nexum Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <HomePage />
      </div>
    </div>
  );
};

export default Home;
